name: Production Deployment
on:
  push:
    branches: [main]

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Yandex Cloud CLI
        run: |
          # Установите Yandex Cloud CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          # Добавьте путь к yc в PATH для текущего процесса
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # Проверьте доступность yc
          echo 'Checking yc CLI version...'
          yc --version
          # Инициализируйте yc с использованием нового токена
          yc init --oauth-token ${{ secrets.YANDEX_CLOUD_REFRESH_TOKEN }}

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_ENV_URL: "envUrl=http://habrapp.example.com"
