name: Production Deployment
on:
  push:
    branches: [main]

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

     # - name: Set up Yandex Cloud CLI
     #   uses: okar1/yc-cli-install@master

     # - name: Initialize YC CLI
     #   run: |
     #     yc init --oauth-token ${{ secrets.YANDEX_CLOUD_REFRESH_TOKEN }}

      - name: Converge
        uses: werf/actions/converge@v1.2
        with:
          env: production
          kube-config-base64-data: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
        env:
          WERF_SET_ENV_URL: "envUrl=http://habrapp.example.com"
